// Generated from data/destinations.json during Sesja C3.
// CITY_PL contains verified Polish display names: established exonyms
// plus same-spelling city names where Polish usage keeps the local form.
// Do not hand-edit individual rows here; update the seed/localization pass instead.

const CITY_PL_SAME_AS_EN = [
  "Barcelona",
  "Malaga",
  "Alicante",
  "Las Palmas",
  "Bilbao",
  "Granada",
  "Faro",
  "Funchal",
  "Ponta Delgada",
  "Porto",
  "Braga",
  "Coimbra",
  "Bari",
  "Palermo",
  "Cagliari",
  "Olbia",
  "Bordeaux",
  "Lyon",
  "Cannes",
  "Lille",
  "Montpellier",
  "Nantes",
  "Chania",
  "Heraklion",
  "Kos",
  "Zakynthos",
  "Limassol",
  "Sliema",
  "Valletta",
  "Antalya",
  "Izmir",
  "Ankara",
  "Bodrum",
  "Dalaman",
  "Agadir",
  "Casablanca",
  "Trabzon",
  "Rabat",
  "Hurghada",
  "Hammamet",
  "Tunis",
  "Split",
  "Tirana",
  "Pula",
  "Zadar",
  "Rijeka",
  "Bled",
  "Piran",
  "Graz",
  "Innsbruck",
  "Salzburg",
  "Berlin",
  "Hamburg",
  "Frankfurt",
  "Amsterdam",
  "Rotterdam",
  "Utrecht",
  "Eindhoven",
  "Cork",
  "Dublin",
  "Galway",
  "Killarney",
  "Manchester",
  "Birmingham",
  "Bristol",
  "Glasgow",
  "Liverpool",
  "Belfast",
  "Brno",
  "Aarhus",
  "Bergen",
  "Helsinki",
  "Oslo",
  "Reykjavik",
  "Sofia",
  "Aabenraa",
  "Aagtekerke",
  "Aalbaek",
  "Aalborg",
  "Aalen",
  "Aalsmeer",
  "Aalst",
  "Aalten",
  "Aalter",
  "Äänekoski",
  "Abádszalók",
  "Abbeville",
  "Abbey Wood",
  "Aberaeron",
  "Aberdare",
  "Aberdaron",
  "Aberdeen",
  "Aberdyfi",
  "Aberfeldy",
  "Aberffraw",
  "Abergavenny",
  "Abergele",
  "Aberlour",
  "Aberporth",
  "Abersoch",
  "Abertamy",
  "Aberystwyth",
  "Abingdon",
  "Aboyne",
  "Abstatt",
  "Abtenau",
  "Abu Dabab",
  "Abu Simbel",
  "Accrington",
  "Acharacle",
  "Achenkirch",
  "Achern",
  "Achílleion",
  "Achim",
  "Achladies",
  "Achlia",
  "Achnasheen",
  "Adalar",
  "Adamas",
  "Adana",
  "Adelboden",
  "Adelianos Kampos",
  "Adenau",
  "Adrasan",
  "Aegina",
  "Aegina Town",
  "Ærøskøbing",
  "Afferden",
  "Afife",
  "Afionas",
  "Afissos",
  "Afitos",
  "Afyon",
  "Agafay",
  "Agde",
  "Agen",
  "Agettes",
  "Aghia Marina",
  "Aghouatim",
  "Agia Anna Naxos",
  "Agia Galini",
  "Agva",
  "Ahaus",
  "Ahlbeck",
  "Ahrensbök",
  "Ahrensburg",
  "Ahrenshoop",
  "Ähtäri",
  "Åhus",
  "Aich",
  "Aigen im Ennstal",
  "Ajaccio",
  "Ajdovščina",
  "Äkäslompolo",
  "Akçaabat",
  "Akcakoca",
  "Åkersberga",
  "Akkrum",
  "Aksaray",
  "Akureyri",
  "Akyaka",
  "Al Aqah",
  "Al Aqālitah",
  "Al Maqārisah",
  "Al-Hammam",
  "Alacati",
  "Alanya",
  "Alba Iulia",
  "Albacete",
  "Albena",
  "Ålesund",
  "Alghero",
  "Alkmaar",
  "Allingåbro",
  "Almere",
  "Almería",
  "Alpbach",
  "Alsóörs",
  "Alta",
  "Altaussee",
  "Altenmarkt im Pongau",
  "Altmünster",
  "Alveringem",
  "Amden",
  "Amersfoort",
  "Amstelveen",
  "Amstetten",
  "Åndalsnes",
  "Andenes",
  "Andenne",
  "Andermatt",
  "Andijk",
  "Angers",
  "Anhée",
  "Anjum",
  "Ankaran",
  "Anloo",
  "Anniviers",
  "Ansager",
  "Antoing",
  "Anzère",
  "Apeldoorn",
  "Appelscha",
  "Appenzell",
  "Arad",
  "Arbon",
  "Arcen",
  "Ardara",
  "Arendal",
  "Argaka",
  "Ariana",
  "Arilje",
  "Årjäng",
  "Arnemuiden",
  "Arnhem",
  "Arosa",
  "Ascona",
  "Asker",
  "Asnæs",
  "Assens",
  "Ataqah",
  "Athlone",
  "Athy",
  "Aurillac",
  "Aurland",
  "Avrig",
  "Aywaille",
  "Azuga",
  "Baarland",
  "Baarle-Nassau",
  "Babino Polje",
  "Bacău",
  "Badajoz",
  "Baderna",
  "Badhoevedorp",
  "Baia de Fier",
  "Baia Mare",
  "Băile Govora",
  "Bajina Bašta",
  "Bajram Curri",
  "Bakar",
  "Baks-Rrjoll",
  "Balatonakarattya",
  "Balatonalmádi",
  "Balen",
  "Baligród",
  "Ballina",
  "Ballybunion",
  "Banja Koviljača",
  "Banovci",
  "Bansko",
  "Barat",
  "Barban",
  "Barbariga",
  "Barbat na Rabu",
  "Barić Draga",
  "Bašanija",
  "Baška",
  "Baška Voda",
  "Bast",
  "Bastia",
  "Bastogne",
  "Batajnica",
  "Bečej",
  "Bechyně",
  "Bedřichov",
  "Bela Crkva",
  "Bělá pod Pradědem",
  "Bele Vode",
  "Beli Iskar",
  "Benecko",
  "Benešov",
  "Benkovac",
  "Berat",
  "Bergerac",
  "Beroun",
  "Betina",
  "Bežanija",
  "Béziers",
  "Biarritz",
  "Bilice",
  "Bindslev",
  "Biograd na Moru",
  "Birgu",
  "Birkirkara",
  "Blackpool",
  "Blansko",
  "Blavand",
  "Blokhus",
  "Bodo",
  "Bogense",
  "Bohinjska Bela",
  "Bohinjska Bistrica",
  "Bolzano",
  "Borgarnes",
  "Børkop",
  "Borre",
  "Bournemouth",
  "Bovec",
  "Bragança",
  "Brest",
  "Brezno",
  "Brindisi",
  "Brive-la-Gaillarde",
  "Brzeće",
  "Búðardalur",
  "Burgas",
  "Burgas City",
  "Burgos",
  "Bursa",
  "Business Bay",
  "Bydgoszcz",
  "Bystrá",
  "Caen",
  "Calvi",
  "Cambridge",
  "Campbeltown",
  "Çanakkale",
  "Carcassonne",
  "Cardiff",
  "Carthage",
  "Castres",
  "Čatež ob Savi",
  "Celje",
  "Cerknica",
  "Châlons-en-Champagne",
  "Chambéry",
  "Chester",
  "Chios",
  "Chott Meriem",
  "Clermont-Ferrand",
  "Comiso",
  "Coral Bay",
  "Coventry",
  "Crotone",
  "Cuneo",
  "Dar Mimoun Bey",
  "Dar Salah Bey",
  "Deauville",
  "Denizli",
  "Dinard",
  "Djerba Midun",
  "Dobrovo",
  "Dole",
  "Doncaster",
  "Donegal",
  "Dortmund",
  "Douar el Hafey",
  "Droushia",
  "Dundee",
  "Durrës",
  "Düsseldorf",
  "Edremit",
  "Egilsstaðir",
  "El Aouina",
  "Elbasan",
  "Erfurt",
  "Erzincan",
  "Erzurum",
  "Esbjerg",
  "Esentepe",
  "Espoo",
  "Exeter",
  "Famagusta",
  "Fier",
  "Figari",
  "Foggia",
  "Forlì",
  "Forssa",
  "Friedrichshafen",
  "Garðabær",
  "Gaziantep",
  "Gazipasa",
  "Gdańsk",
  "Għajnsielem",
  "Għarb",
  "Għasri",
  "Girona",
  "Golem",
  "Grenoble",
  "Groningen",
  "Haapsalu",
  "Hafnarfjörður",
  "Halmstad",
  "Hämeenlinna",
  "Hanko",
  "Haugesund",
  "Hella",
  "Heringsdorf",
  "Ibiza",
  "Il-Pergla",
  "Inverness",
  "Isparta",
  "Ivalo",
  "Jerez de la Frontera",
  "Joensuu",
  "Jonkoping",
  "Jyväskylä",
  "Kajaani",
  "Kalamata",
] as const;

const CITY_PL_EXONYMS = {
  "Aachen": "Akwizgran",
  "Abu Dhabi": "Abu Zabi",
  "Acharavi": "Acharawi",
  "Aeroskobing": "Ærøskøbing",
  "Afantou": "Afandu",
  "Afritz": "Afritz am See",
  "Agdz": "Akdaz",
  "Aghīr": "Aghireș",
  "Agros": "Mietlica",
  "Aheloy": "Achełoj (obwód Burgas)",
  "Ahtopol": "Achtopol",
  "Ain Sokhna": "Ajn Suchna",
  "Aït Ben Haddou": "Ajt Bin Haddu",
  "Aït Benhaddou": "Ajt Bin Haddu",
  "Ajman": "Adżman",
  "Akirkeby": "Aakirkeby",
  "Ål": "Albania",
  "Al Ain": "Al-Ajn",
  "Al Hoceïma": "Al-Husajma",
  "Al-Fujairah": "Al-Fujairah FC",
  "Albac": "Gmina Albac",
  "Alexandria": "Aleksandria",
  "Alingsas": "gmina Alingsås",
  "Allinge": "Allinge-Sandvig",
  "Alytus": "Olita",
  "Ancona": "Ankona",
  "Angelholm": "Ängelholm",
  "Antakya": "Antiochia",
  "Antwerp": "Antwerpia",
  "Anykščiai": "Onikszty",
  "Apriltsi": "Gmina Apriłci",
  "Arandjelovac": "Aranđelovac",
  "Are": "Zjednoczone Emiraty Arabskie",
  "Arieşeni": "Gmina Arieșeni",
  "Arrecife": "Lanzarote",
  "Arvidsjaur": "gmina Arvidsjaur",
  "Asenovgrad": "Asenowgrad",
  "Asnaes": "Asnæs",
  "Aswan": "Asuan",
  "Athens": "Ateny",
  "Aughrim": "Aughrim (hrabstwo Galway)",
  "Avignon": "Awinion",
  "Ayia Marina Chrysochous": "Ajia Marina Chrisochus",
  "Ayia Napa": "Ajia Napa",
  "Babići": "Băbiciu (gmina)",
  "Baia-Sprie": "Baia Sprie",
  "Baile Felix": "Băile Felix",
  "Băile Olăneşti": "Băile Olănești",
  "Baja": "Kalifornia Dolna Południowa",
  "Balatonfůzfő": "Balatonfűzfő",
  "Balchik": "Bałczik",
  "Bale": "Bazylea",
  "Banjol": "ukulele",
  "Banjole": "ukulele",
  "Banská Bystrica": "Bańska Bystrzyca",
  "Banya": "budynek",
  "Bardejov": "Bardejów",
  "Basel": "Bazylea",
  "Bataypora": "Batayporã",
  "Belgrade": "Belgrad",
  "Bešeňová": "Beszeniowa",
  "Bibinje": "Gmina Bibinje",
  "Billund": "Gmina Billund",
  "Birštonas": "Birsztany",
  "Birzebbuga": "Birżebbuġa",
  "Bizerte": "Bizerta",
  "Bjert": "Bjertnæs",
  "Blagoevgrad": "Błagojewgrad",
  "Bláskógabyggd": "Bláskógabyggð",
  "Bohinj": "Gmina Bohinj",
  "Bol": "Boliwia",
  "Bologna": "Bolonia",
  "Bor": "Bor (miasto w Czechach)",
  "Borkop": "Gmina Børkop",
  "Borovets": "Borowec",
  "Braşov": "Okręg Braszów",
  "Bratislava": "Bratysława",
  "Bremen": "Brema",
  "Brežice": "Gmina Brežice",
  "Bruges": "Brugia",
  "Brussels": "Bruksela",
  "Bucharest": "Bukareszt",
  "Budapest": "Budapeszt",
  "Budardalur": "Búðardalur",
  "Byala": "Bjała",
  "Cairo": "Kair",
  "Castellón de la Plana": "Castelló de la Plana",
  "Catania": "Katania",
  "Cerklje na Gorenjskem": "Gmina Cerklje na Gorenjskem",
  "Cerkno": "Gmina Cerkno",
  "Cēsis": "Kieś",
  "Chepelare": "Czepełare",
  "Chernomorets": "Czernomorec",
  "Chlorakas": "Chloraka",
  "Cluj-Napoca": "Kluż-Napoka",
  "Cologne": "Kolonia",
  "Constanţa": "Konstanca",
  "Copenhagen": "Kopenhaga",
  "Cordoba": "Kordoba",
  "Corfu": "Korfu",
  "Cospicua": "Bormla",
  "Córdoba": "Kordoba",
  "Craiova": "Krajowa",
  "Crnomelj": "Gmina Črnomelj",
  "Dakhla": "Ad-Dachla",
  "Debrecen": "Debreczyn",
  "Divjakë": "Divjaka",
  "Diyarbakir": "Diyarbakır",
  "Djerba": "Dżerba",
  "Dolenjske Toplice": "Gmina Dolenjske Toplice",
  "Douz": "Douzens",
  "Dresden": "Drezno",
  "Druskininkai": "Druskieniki",
  "Dubai": "Dubaj",
  "Dubrovnik": "Dubrownik",
  "Dusseldorf": "Düsseldorf",
  "Edinburgh": "Edynburg",
  "Egilsstadir": "Egilsstaðir",
  "El Haouaria": "Al-Hawarijja",
  "Elazig": "Elazığ",
  "Eskisehir": "Eskişehir",
  "Essaouira": "As-Sawira",
  "Fira": "Fira (Santorini)",
  "Florence": "Florencja",
  "Fujairah": "Fudżajra",
  "Gdansk": "Gdańsk",
  "Geneva": "Genewa",
  "Genoa": "Genua",
  "Ghajnsielem": "Għajnsielem",
  "Gharb": "Għarb",
  "Ghasri": "Għasri",
  "Ghent": "Gandawa",
  "Goreme": "Göreme",
  "Gothenburg": "Göteborg",
  "Gzira": "wyspa",
  "Hafnarfjördur": "Hafnarfjörður",
  "Hamrun": "Ħamrun",
  "Iaşi": "Jassy",
  "Ibiza Town": "Ibiza",
  "Il-Furjana": "Floriana",
  "Il-Gżira": "Gżira",
  "Ioannina": "Janina",
  "Is-Swieqi": "Swieqi",
  "Istanbul": "Stambuł",
  "Izmit": "İzmit",
  "Kahramanmaras": "Kahramanmaraş",
  "Kalymnos": "Kalimnos",
  "Karlovy Vary": "Karlowe Wary",
  "Kaunas": "Kowno",
  "Klagenfurt": "Klagenfurt am Wörthersee",
  "Košice": "Koszyce",
  "Krakow": "Kraków",
  "Kutahya": "Kütahya",
  "Larnaca": "Larnaka",
  "Lisbon": "Lizbona",
  "Ljubljana": "Lublana",
  "Lodz": "Łódź",
  "London": "Londyn",
  "Lucerne": "Lucerna",
  "Luxor": "Luksor",
  "Madrid": "Madryt",
  "Málaga": "Malaga",
  "Malmo": "Malmö",
  "Marrakech": "Marrakesz",
  "Marrakesh": "Marrakesz",
  "Marseille": "Marsylia",
  "Mellieha": "Mellieħa",
  "Milan": "Mediolan",
  "Milos": "Miloš",
  "Monastir": "Bitola",
  "Mosjoen": "Mosjøen",
  "Mosta": "Mostar",
  "Munich": "Monachium",
  "Naples": "Neapol",
  "Nevsehir": "Nevşehir",
  "Nice": "Nicea",
  "Nicosia": "Nikozja",
  "Niš": "Nicea",
  "Nuremberg": "Norymberga",
  "Ostrava": "Ostrawa",
  "Ouarzazate": "Warzazat",
  "Oujda": "Wadżda",
  "Palanga": "Połąga",
  "Palma": "Palma de Mallorca",
  "Pamplona": "Pampeluna",
  "Paphos": "Pafos",
  "Paris": "Paryż",
  "Pécs": "Pecz",
  "Pietà": "Pieta",
  "Pisa": "Piza",
  "Plovdiv": "Płowdiw",
  "Prague": "Praga",
  "Preveza": "Preweza",
  "Ras al Khaimah": "Ras al-Chajma",
  "Rhodes": "Rodos",
  "Riga": "Ryga",
  "Rīga": "Ryga",
  "Rome": "Rzym",
  "Roros": "Røros",
  "San Sebastian": "San Sebastián",
  "San Sebastián de la Gomera": "San Sebastián de La Gomera",
  "Santa Cruz de Tenerife": "Teneryfa",
  "Sarande": "Sarandë",
  "Seville": "Sewilla",
  "Sfax": "Sfax (1934)",
  "Sharjah": "Szardża",
  "Sharm El Sheikh": "Szarm el-Szejk",
  "Sibiu": "Sybin",
  "Sinop": "Synopa",
  "Sitia": "Sitía",
  "Skiros": "Skyros",
  "Sousse": "Susa",
  "St Julian's": "St. Julian's",
  "Stockholm": "Sztokholm",
  "Strasbourg": "Strasburg",
  "Suceava": "Suczawa",
  "Taba": "bąkowate",
  "Tallinn": "Tallin",
  "Tangier": "Tanger",
  "Tekirdag": "Tekirdağ",
  "The Hague": "Haga",
  "Thessaloniki": "Saloniki",
  "Timişoara": "Timișoara",
  "Torsby": "Gmina Torsby",
  "Toulon": "Tulon",
  "Toulouse": "Tuluza",
  "Tozeur": "Tauzar",
  "Tromso": "Tromsø",
  "Turin": "Turyn",
  "Valencia": "Walencja",
  "Valley": "dolina",
  "Van": "Wan",
  "Varna": "Vahrn",
  "Venice": "Wenecja",
  "Verona": "Werona",
  "Vienna": "Wiedeń",
  "Vila Real": "Vila-real",
  "Vilnius": "Wilno",
  "Vlore": "Wlora",
  "Volos": "Wolos",
  "Warsaw": "Warszawa",
  "Wroclaw": "Wrocław",
  "Zagreb": "Zagrzeb",
  "Zurich": "Zurych",
  "Zürich": "Zurych",
} as const;

export const CITY_PL_GENERATED: Record<string, string> = {
  ...Object.fromEntries(CITY_PL_SAME_AS_EN.map((city) => [city, city])),
  ...CITY_PL_EXONYMS,
};
