import type { DestinationProfile } from "./types";

function links(city: string, country: string) {
  const place = `${city} ${country}`;
  return {
    flights: `https://www.google.com/search?q=${encodeURIComponent(`loty z Polski do ${place}`)}`,
    stays: `https://www.booking.com/searchresults.pl.html?ss=${encodeURIComponent(place)}`,
    attractions: `https://www.google.com/search?q=${encodeURIComponent(`${place} atrakcje`)}`,
  };
}

export const curatedDestinations: DestinationProfile[] = [
  {
    id: "dest_lisbon",
    slug: "lisbon-portugal",
    city: "Lisbon",
    country: "Portugal",
    visaForPL: true,
    avgTempByMonth: [15, 16, 18, 19, 22, 25, 28, 28, 26, 22, 18, 16],
    costIndex: 1.2,
    beachScore: 0.75,
    cityScore: 0.9,
    sightseeingScore: 0.9,
    nightlifeScore: 0.8,
    natureScore: 0.6,
    safetyScore: 0.8,
    accessScore: 0.8,
    typicalFlightHoursFromPL: 4.0,
    affiliateLinks: links("Lisbon", "Portugal"),
  },
  {
    id: "dest_barcelona",
    slug: "barcelona-spain",
    city: "Barcelona",
    country: "Spain",
    visaForPL: true,
    avgTempByMonth: [13, 14, 16, 18, 21, 25, 28, 29, 26, 22, 17, 14],
    costIndex: 1.35,
    beachScore: 0.9,
    cityScore: 0.95,
    sightseeingScore: 0.95,
    nightlifeScore: 0.9,
    natureScore: 0.55,
    safetyScore: 0.78,
    accessScore: 0.82,
    typicalFlightHoursFromPL: 3.0,
    affiliateLinks: links("Barcelona", "Spain"),
  },
  {
    id: "dest_valencia",
    slug: "valencia-spain",
    city: "Valencia",
    country: "Spain",
    visaForPL: true,
    avgTempByMonth: [14, 15, 17, 19, 22, 26, 29, 30, 27, 23, 18, 15],
    costIndex: 1.1,
    beachScore: 0.88,
    cityScore: 0.8,
    sightseeingScore: 0.82,
    nightlifeScore: 0.7,
    natureScore: 0.65,
    safetyScore: 0.8,
    accessScore: 0.76,
    typicalFlightHoursFromPL: 3.2,
    affiliateLinks: links("Valencia", "Spain"),
  },
  {
    id: "dest_malaga",
    slug: "malaga-spain",
    city: "Malaga",
    country: "Spain",
    visaForPL: true,
    avgTempByMonth: [15, 16, 18, 20, 23, 27, 30, 30, 27, 23, 18, 16],
    costIndex: 1.08,
    beachScore: 0.92,
    cityScore: 0.84,
    sightseeingScore: 0.87,
    nightlifeScore: 0.7,
    natureScore: 0.66,
    safetyScore: 0.82,
    accessScore: 0.8,
    typicalFlightHoursFromPL: 3.4,
    affiliateLinks: links("Malaga", "Spain"),
  },
  {
    id: "dest_rome",
    slug: "rome-italy",
    city: "Rome",
    country: "Italy",
    visaForPL: true,
    avgTempByMonth: [12, 13, 15, 18, 22, 27, 30, 30, 26, 22, 17, 13],
    costIndex: 1.35,
    beachScore: 0.45,
    cityScore: 0.98,
    sightseeingScore: 1.0,
    nightlifeScore: 0.75,
    natureScore: 0.5,
    safetyScore: 0.77,
    accessScore: 0.86,
    typicalFlightHoursFromPL: 2.2,
    affiliateLinks: links("Rome", "Italy"),
  },
  {
    id: "dest_naples",
    slug: "naples-italy",
    city: "Naples",
    country: "Italy",
    visaForPL: true,
    avgTempByMonth: [11, 12, 14, 17, 21, 25, 29, 29, 25, 21, 16, 12],
    costIndex: 1.05,
    beachScore: 0.7,
    cityScore: 0.8,
    sightseeingScore: 0.86,
    nightlifeScore: 0.68,
    natureScore: 0.7,
    safetyScore: 0.7,
    accessScore: 0.74,
    typicalFlightHoursFromPL: 2.3,
    affiliateLinks: links("Naples", "Italy"),
  },
  {
    id: "dest_athens",
    slug: "athens-greece",
    city: "Athens",
    country: "Greece",
    visaForPL: true,
    avgTempByMonth: [12, 13, 15, 19, 24, 29, 32, 32, 28, 23, 18, 14],
    costIndex: 1.0,
    beachScore: 0.84,
    cityScore: 0.8,
    sightseeingScore: 0.9,
    nightlifeScore: 0.72,
    natureScore: 0.6,
    safetyScore: 0.76,
    accessScore: 0.72,
    typicalFlightHoursFromPL: 2.6,
    affiliateLinks: links("Athens", "Greece"),
  },
  {
    id: "dest_larnaca",
    slug: "larnaca-cyprus",
    city: "Larnaca",
    country: "Cyprus",
    visaForPL: true,
    avgTempByMonth: [17, 17, 19, 22, 26, 30, 33, 33, 31, 28, 23, 19],
    costIndex: 1.1,
    beachScore: 0.95,
    cityScore: 0.64,
    sightseeingScore: 0.7,
    nightlifeScore: 0.66,
    natureScore: 0.6,
    safetyScore: 0.82,
    accessScore: 0.68,
    typicalFlightHoursFromPL: 3.2,
    affiliateLinks: links("Larnaca", "Cyprus"),
  },
  {
    id: "dest_valletta",
    slug: "valletta-malta",
    city: "Valletta",
    country: "Malta",
    visaForPL: true,
    avgTempByMonth: [15, 15, 17, 19, 23, 28, 31, 31, 28, 25, 21, 17],
    costIndex: 1.18,
    beachScore: 0.82,
    cityScore: 0.78,
    sightseeingScore: 0.82,
    nightlifeScore: 0.68,
    natureScore: 0.55,
    safetyScore: 0.85,
    accessScore: 0.68,
    typicalFlightHoursFromPL: 3.1,
    affiliateLinks: links("Valletta", "Malta"),
  },
  {
    id: "dest_tirana",
    slug: "tirana-albania",
    city: "Tirana",
    country: "Albania",
    visaForPL: true,
    avgTempByMonth: [7, 9, 12, 16, 21, 26, 30, 30, 25, 19, 13, 9],
    costIndex: 0.78,
    beachScore: 0.7,
    cityScore: 0.7,
    sightseeingScore: 0.68,
    nightlifeScore: 0.64,
    natureScore: 0.8,
    safetyScore: 0.75,
    accessScore: 0.62,
    typicalFlightHoursFromPL: 2.1,
    affiliateLinks: links("Tirana", "Albania"),
  },
  {
    id: "dest_istanbul",
    slug: "istanbul-turkey",
    city: "Istanbul",
    country: "Turkey",
    visaForPL: true,
    avgTempByMonth: [8, 9, 11, 15, 20, 25, 28, 28, 24, 19, 14, 10],
    costIndex: 0.85,
    beachScore: 0.62,
    cityScore: 0.95,
    sightseeingScore: 0.95,
    nightlifeScore: 0.8,
    natureScore: 0.55,
    safetyScore: 0.68,
    accessScore: 0.8,
    typicalFlightHoursFromPL: 2.2,
    affiliateLinks: links("Istanbul", "Turkey"),
  },
  {
    id: "dest_antalya",
    slug: "antalya-turkey",
    city: "Antalya",
    country: "Turkey",
    visaForPL: true,
    avgTempByMonth: [11, 12, 15, 19, 24, 30, 34, 34, 30, 24, 17, 13],
    costIndex: 0.9,
    beachScore: 0.98,
    cityScore: 0.65,
    sightseeingScore: 0.7,
    nightlifeScore: 0.68,
    natureScore: 0.62,
    safetyScore: 0.7,
    accessScore: 0.74,
    typicalFlightHoursFromPL: 3.0,
    affiliateLinks: links("Antalya", "Turkey"),
  },
  {
    id: "dest_marrakesh",
    slug: "marrakesh-morocco",
    city: "Marrakesh",
    country: "Morocco",
    visaForPL: true,
    avgTempByMonth: [18, 20, 23, 26, 30, 35, 38, 38, 33, 28, 23, 19],
    costIndex: 0.82,
    beachScore: 0.25,
    cityScore: 0.85,
    sightseeingScore: 0.86,
    nightlifeScore: 0.55,
    natureScore: 0.62,
    safetyScore: 0.65,
    accessScore: 0.6,
    typicalFlightHoursFromPL: 4.5,
    affiliateLinks: links("Marrakesh", "Morocco"),
  },
  {
    id: "dest_agadir",
    slug: "agadir-morocco",
    city: "Agadir",
    country: "Morocco",
    visaForPL: true,
    avgTempByMonth: [20, 21, 23, 24, 25, 27, 30, 30, 28, 26, 24, 21],
    costIndex: 0.8,
    beachScore: 0.92,
    cityScore: 0.55,
    sightseeingScore: 0.62,
    nightlifeScore: 0.5,
    natureScore: 0.72,
    safetyScore: 0.68,
    accessScore: 0.62,
    typicalFlightHoursFromPL: 4.6,
    affiliateLinks: links("Agadir", "Morocco"),
  },
  {
    id: "dest_budapest",
    slug: "budapest-hungary",
    city: "Budapest",
    country: "Hungary",
    visaForPL: true,
    avgTempByMonth: [1, 4, 9, 14, 19, 23, 26, 26, 21, 15, 8, 3],
    costIndex: 0.85,
    beachScore: 0.15,
    cityScore: 0.9,
    sightseeingScore: 0.88,
    nightlifeScore: 0.82,
    natureScore: 0.48,
    safetyScore: 0.82,
    accessScore: 0.9,
    typicalFlightHoursFromPL: 1.2,
    affiliateLinks: links("Budapest", "Hungary"),
  },
  {
    id: "dest_prague",
    slug: "prague-czechia",
    city: "Prague",
    country: "Czechia",
    visaForPL: true,
    avgTempByMonth: [0, 2, 7, 12, 17, 20, 23, 23, 18, 12, 6, 2],
    costIndex: 0.9,
    beachScore: 0.08,
    cityScore: 0.95,
    sightseeingScore: 0.92,
    nightlifeScore: 0.84,
    natureScore: 0.4,
    safetyScore: 0.86,
    accessScore: 0.92,
    typicalFlightHoursFromPL: 1.0,
    affiliateLinks: links("Prague", "Czechia"),
  },
  {
    id: "dest_berlin",
    slug: "berlin-germany",
    city: "Berlin",
    country: "Germany",
    visaForPL: true,
    avgTempByMonth: [2, 3, 8, 13, 18, 21, 24, 24, 19, 13, 7, 3],
    costIndex: 1.25,
    beachScore: 0.08,
    cityScore: 0.9,
    sightseeingScore: 0.84,
    nightlifeScore: 0.92,
    natureScore: 0.45,
    safetyScore: 0.82,
    accessScore: 0.92,
    typicalFlightHoursFromPL: 1.4,
    affiliateLinks: links("Berlin", "Germany"),
  },
  {
    id: "dest_amsterdam",
    slug: "amsterdam-netherlands",
    city: "Amsterdam",
    country: "Netherlands",
    visaForPL: true,
    avgTempByMonth: [4, 5, 8, 11, 15, 18, 21, 21, 18, 14, 9, 5],
    costIndex: 1.65,
    beachScore: 0.22,
    cityScore: 0.94,
    sightseeingScore: 0.86,
    nightlifeScore: 0.88,
    natureScore: 0.42,
    safetyScore: 0.85,
    accessScore: 0.9,
    typicalFlightHoursFromPL: 1.9,
    affiliateLinks: links("Amsterdam", "Netherlands"),
  },
  {
    id: "dest_dublin",
    slug: "dublin-ireland",
    city: "Dublin",
    country: "Ireland",
    visaForPL: true,
    avgTempByMonth: [6, 6, 8, 10, 13, 16, 19, 19, 16, 13, 9, 7],
    costIndex: 1.4,
    beachScore: 0.2,
    cityScore: 0.8,
    sightseeingScore: 0.74,
    nightlifeScore: 0.84,
    natureScore: 0.68,
    safetyScore: 0.88,
    accessScore: 0.82,
    typicalFlightHoursFromPL: 2.8,
    affiliateLinks: links("Dublin", "Ireland"),
  },
  {
    id: "dest_london",
    slug: "london-uk",
    city: "London",
    country: "United Kingdom",
    visaForPL: false,
    avgTempByMonth: [7, 8, 10, 13, 17, 20, 23, 23, 20, 15, 11, 8],
    costIndex: 1.8,
    beachScore: 0.04,
    cityScore: 1.0,
    sightseeingScore: 0.95,
    nightlifeScore: 0.9,
    natureScore: 0.4,
    safetyScore: 0.82,
    accessScore: 0.95,
    typicalFlightHoursFromPL: 2.5,
    affiliateLinks: links("London", "United Kingdom"),
  },
  {
    id: "dest_las_palmas",
    slug: "las-palmas-spain",
    city: "Las Palmas",
    country: "Spain",
    visaForPL: true,
    avgTempByMonth: [21, 21, 22, 23, 24, 25, 27, 28, 27, 26, 24, 22],
    costIndex: 1.2,
    beachScore: 0.95,
    cityScore: 0.64,
    sightseeingScore: 0.68,
    nightlifeScore: 0.62,
    natureScore: 0.84,
    safetyScore: 0.84,
    accessScore: 0.52,
    typicalFlightHoursFromPL: 5.7,
    affiliateLinks: links("Las Palmas", "Spain"),
  },
  {
    id: "dest_funchal",
    slug: "funchal-portugal",
    city: "Funchal",
    country: "Portugal",
    visaForPL: true,
    avgTempByMonth: [19, 19, 20, 20, 22, 24, 26, 27, 26, 24, 22, 20],
    costIndex: 1.22,
    beachScore: 0.58,
    cityScore: 0.62,
    sightseeingScore: 0.72,
    nightlifeScore: 0.5,
    natureScore: 0.94,
    safetyScore: 0.86,
    accessScore: 0.55,
    typicalFlightHoursFromPL: 5.4,
    affiliateLinks: links("Funchal", "Portugal"),
  },
];
