import { normalizeLookup, resolveAirportCode } from "./location";

export interface DestinationCatalogEntry {
  slug: string;
  city: string;
  country: string;
  label: string;
  airportCode?: string;
}

type DestinationSeed = readonly [city: string, country: string];

const DESTINATION_SEEDS: DestinationSeed[] = [
  ["Malaga", "Spain"],
  ["Barcelona", "Spain"],
  ["Valencia", "Spain"],
  ["Madrid", "Spain"],
  ["Seville", "Spain"],
  ["Alicante", "Spain"],
  ["Palma", "Spain"],
  ["Las Palmas", "Spain"],
  ["Ibiza Town", "Spain"],
  ["Bilbao", "Spain"],
  ["Granada", "Spain"],
  ["San Sebastian", "Spain"],
  ["Cordoba", "Spain"],
  ["Santa Cruz de Tenerife", "Spain"],
  ["Arrecife", "Spain"],
  ["Lisbon", "Portugal"],
  ["Porto", "Portugal"],
  ["Funchal", "Portugal"],
  ["Faro", "Portugal"],
  ["Ponta Delgada", "Portugal"],
  ["Coimbra", "Portugal"],
  ["Braga", "Portugal"],
  ["Rome", "Italy"],
  ["Naples", "Italy"],
  ["Milan", "Italy"],
  ["Venice", "Italy"],
  ["Florence", "Italy"],
  ["Bologna", "Italy"],
  ["Turin", "Italy"],
  ["Palermo", "Italy"],
  ["Catania", "Italy"],
  ["Bari", "Italy"],
  ["Verona", "Italy"],
  ["Pisa", "Italy"],
  ["Genoa", "Italy"],
  ["Cagliari", "Italy"],
  ["Olbia", "Italy"],
  ["Paris", "France"],
  ["Nice", "France"],
  ["Marseille", "France"],
  ["Lyon", "France"],
  ["Bordeaux", "France"],
  ["Toulouse", "France"],
  ["Strasbourg", "France"],
  ["Nantes", "France"],
  ["Lille", "France"],
  ["Cannes", "France"],
  ["Montpellier", "France"],
  ["Athens", "Greece"],
  ["Thessaloniki", "Greece"],
  ["Heraklion", "Greece"],
  ["Chania", "Greece"],
  ["Corfu", "Greece"],
  ["Rhodes", "Greece"],
  ["Fira", "Greece"],
  ["Mykonos Town", "Greece"],
  ["Zakynthos", "Greece"],
  ["Kos", "Greece"],
  ["Larnaca", "Cyprus"],
  ["Paphos", "Cyprus"],
  ["Nicosia", "Cyprus"],
  ["Limassol", "Cyprus"],
  ["Valletta", "Malta"],
  ["Sliema", "Malta"],
  ["St Julian's", "Malta"],
  ["Istanbul", "Turkey"],
  ["Antalya", "Turkey"],
  ["Izmir", "Turkey"],
  ["Bodrum", "Turkey"],
  ["Ankara", "Turkey"],
  ["Dalaman", "Turkey"],
  ["Goreme", "Turkey"],
  ["Trabzon", "Turkey"],
  ["Marrakesh", "Morocco"],
  ["Agadir", "Morocco"],
  ["Casablanca", "Morocco"],
  ["Fez", "Morocco"],
  ["Tangier", "Morocco"],
  ["Rabat", "Morocco"],
  ["Cairo", "Egypt"],
  ["Hurghada", "Egypt"],
  ["Sharm El Sheikh", "Egypt"],
  ["Alexandria", "Egypt"],
  ["Luxor", "Egypt"],
  ["Tunis", "Tunisia"],
  ["Hammamet", "Tunisia"],
  ["Sousse", "Tunisia"],
  ["Djerba", "Tunisia"],
  ["Tirana", "Albania"],
  ["Sarande", "Albania"],
  ["Vlore", "Albania"],
  ["Split", "Croatia"],
  ["Dubrovnik", "Croatia"],
  ["Zagreb", "Croatia"],
  ["Zadar", "Croatia"],
  ["Pula", "Croatia"],
  ["Rijeka", "Croatia"],
  ["Kotor", "Montenegro"],
  ["Budva", "Montenegro"],
  ["Tivat", "Montenegro"],
  ["Podgorica", "Montenegro"],
  ["Ljubljana", "Slovenia"],
  ["Bled", "Slovenia"],
  ["Piran", "Slovenia"],
  ["Vienna", "Austria"],
  ["Salzburg", "Austria"],
  ["Innsbruck", "Austria"],
  ["Graz", "Austria"],
  ["Berlin", "Germany"],
  ["Munich", "Germany"],
  ["Hamburg", "Germany"],
  ["Cologne", "Germany"],
  ["Frankfurt", "Germany"],
  ["Dusseldorf", "Germany"],
  ["Dresden", "Germany"],
  ["Nuremberg", "Germany"],
  ["Amsterdam", "Netherlands"],
  ["Rotterdam", "Netherlands"],
  ["The Hague", "Netherlands"],
  ["Utrecht", "Netherlands"],
  ["Eindhoven", "Netherlands"],
  ["Brussels", "Belgium"],
  ["Bruges", "Belgium"],
  ["Antwerp", "Belgium"],
  ["Ghent", "Belgium"],
  ["Dublin", "Ireland"],
  ["Cork", "Ireland"],
  ["Galway", "Ireland"],
  ["Killarney", "Ireland"],
  ["London", "United Kingdom"],
  ["Edinburgh", "United Kingdom"],
  ["Manchester", "United Kingdom"],
  ["Liverpool", "United Kingdom"],
  ["Glasgow", "United Kingdom"],
  ["Birmingham", "United Kingdom"],
  ["Bristol", "United Kingdom"],
  ["Belfast", "United Kingdom"],
  ["Budapest", "Hungary"],
  ["Debrecen", "Hungary"],
  ["Prague", "Czechia"],
  ["Brno", "Czechia"],
  ["Warsaw", "Poland"],
  ["Krakow", "Poland"],
  ["Gdansk", "Poland"],
  ["Copenhagen", "Denmark"],
  ["Aarhus", "Denmark"],
  ["Stockholm", "Sweden"],
  ["Gothenburg", "Sweden"],
  ["Malmo", "Sweden"],
  ["Oslo", "Norway"],
  ["Bergen", "Norway"],
  ["Helsinki", "Finland"],
  ["Reykjavik", "Iceland"],
  ["Zurich", "Switzerland"],
  ["Geneva", "Switzerland"],
  ["Lucerne", "Switzerland"],
  ["Basel", "Switzerland"],
  ["Belgrade", "Serbia"],
  ["Sarajevo", "Bosnia and Herzegovina"],
  ["Skopje", "North Macedonia"],
  ["Sofia", "Bulgaria"],
  ["Bucharest", "Romania"],
  ["Cluj-Napoca", "Romania"],
  ["Riga", "Latvia"],
  ["Vilnius", "Lithuania"],
  ["Tallinn", "Estonia"],
  ["Kaunas", "Lithuania"],
  ["Dubai", "United Arab Emirates"],
  ["Abu Dhabi", "United Arab Emirates"],
  ["Doha", "Qatar"],
  ["Muscat", "Oman"],
  ["Tel Aviv", "Israel"],
  ["Jerusalem", "Israel"],
  ["Amman", "Jordan"],
  ["Riyadh", "Saudi Arabia"],
  ["Bangkok", "Thailand"],
  ["Phuket", "Thailand"],
  ["Krabi", "Thailand"],
  ["Chiang Mai", "Thailand"],
  ["Koh Samui", "Thailand"],
  ["Singapore", "Singapore"],
  ["Kuala Lumpur", "Malaysia"],
  ["Penang", "Malaysia"],
  ["Denpasar", "Indonesia"],
  ["Jakarta", "Indonesia"],
  ["Hanoi", "Vietnam"],
  ["Ho Chi Minh City", "Vietnam"],
  ["Da Nang", "Vietnam"],
  ["Tokyo", "Japan"],
  ["Osaka", "Japan"],
  ["Kyoto", "Japan"],
  ["Seoul", "South Korea"],
  ["Busan", "South Korea"],
  ["Hong Kong", "Hong Kong"],
  ["Taipei", "Taiwan"],
  ["Colombo", "Sri Lanka"],
  ["Male", "Maldives"],
  ["Goa", "India"],
  ["Delhi", "India"],
  ["Mumbai", "India"],
  ["Beijing", "China"],
  ["Shanghai", "China"],
  ["New York", "United States of America"],
  ["Los Angeles", "United States of America"],
  ["San Francisco", "United States of America"],
  ["Miami", "United States of America"],
  ["Las Vegas", "United States of America"],
  ["Chicago", "United States of America"],
  ["Boston", "United States of America"],
  ["Washington", "United States of America"],
  ["Orlando", "United States of America"],
  ["Seattle", "United States of America"],
  ["Toronto", "Canada"],
  ["Vancouver", "Canada"],
  ["Montreal", "Canada"],
  ["Cancun", "Mexico"],
  ["Mexico City", "Mexico"],
  ["Playa del Carmen", "Mexico"],
  ["Punta Cana", "Dominican Republic"],
  ["San Juan", "Puerto Rico"],
  ["Rio de Janeiro", "Brazil"],
  ["Sao Paulo", "Brazil"],
  ["Buenos Aires", "Argentina"],
  ["Lima", "Peru"],
  ["Santiago", "Chile"],
  ["Bogota", "Colombia"],
  ["Cape Town", "South Africa"],
  ["Johannesburg", "South Africa"],
  ["Stone Town", "Tanzania"],
  ["Nairobi", "Kenya"],
  ["Port Louis", "Mauritius"],
  ["Sydney", "Australia"],
  ["Melbourne", "Australia"],
  ["Auckland", "New Zealand"],
  ["Queenstown", "New Zealand"],
];

function slugify(value: string): string {
  return normalizeLookup(value).replace(/\s+/g, "-");
}

export const destinationCatalog: DestinationCatalogEntry[] = DESTINATION_SEEDS.map(([city, country]) => ({
  slug: `${slugify(city)}-${slugify(country)}`,
  city,
  country,
  label: `${city}, ${country}`,
  airportCode: resolveAirportCode(city),
}));

const destinationCatalogMap = new Map(
  destinationCatalog.map((item) => [`${normalizeLookup(item.city)}|${normalizeLookup(item.country)}`, item]),
);

export function getDestinationCatalog(): DestinationCatalogEntry[] {
  return destinationCatalog;
}

export function getDestinationCatalogCount(): number {
  return destinationCatalog.length;
}

export function getDestinationCatalogEntry(input: { city: string; country?: string }): DestinationCatalogEntry | undefined {
  const normalizedCity = normalizeLookup(input.city);
  const normalizedCountry = normalizeLookup(input.country ?? "");

  if (normalizedCountry) {
    return destinationCatalogMap.get(`${normalizedCity}|${normalizedCountry}`);
  }

  return destinationCatalog.find((item) => normalizeLookup(item.city) === normalizedCity);
}
