// WYGENEROWANE przez scripts/seo/month-index-baseline.ts (tryb freeze). Nie edytować ręcznie.
//
// Zamrożony zbiór indeksowalnych stron /kierunki/[slug]/[miesiac]: dokładnie te
// strony, które na produkcji (cd2aaee) miały index i stały w sitemapie. Do cd2aaee
// decydował o tym predykat z temperaturą, która dla 212 z 235 kierunków pochodzi
// z tablicy regionu. Od PR #1.5 temperatura nie steruje indeksem: strona jest
// indeksowalna wtedy i tylko wtedy, gdy stoi w tej bazie. Nowa polityka indeksu
// powstanie po danych klimatycznych i GSC — jako świadoma zmiana tej bazy.

import type { PolishMonthSlug } from "./months";

export const MONTH_INDEX_BASELINE_META = {
  "predicateCommit": "cd2aaee80dd34371ebaad7ff4abafaf3fb52cf57",
  "generatedAtCommit": "3a08096441469225e590e6df85d5f0e41b82fb10",
  "generator": "pnpm exec tsx scripts/seo/month-index-baseline.ts freeze",
  "predicate": "isMonthIndexable z src/lib/mvp/month-index-policy.ts@cd2aaee: kuratorowane/komercyjne ≥ 10°C, plaża ≥ 22°C, city break 16–32°C, grudzień city break",
  "verifiedAgainst": {
    "sitemap": "https://helptravel.pl/sitemap.xml",
    "sitemapMonthUrls": 1039,
    "missingInSitemap": 0,
    "extraInSitemap": 0,
    "checkedAt": "2026-09-15"
  },
  "count": 1039,
  "sha256": "0c70fdd935de71c92fccf9e8c3eb826faa0b66009ea573b1322c74c48b4c2dcb"
} as const;

export const CURRENT_INDEX_BASELINE: Readonly<Record<string, readonly PolishMonthSlug[]>> = {
  "abu-dhabi-united-arab-emirates": ["marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad"],
  "agadir-morocco": ["marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad"],
  "alicante-spain": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien"],
  "amsterdam-netherlands": ["kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "grudzien"],
  "antalya-turkey": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "arrecife-spain": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien"],
  "athens-greece": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "auckland-new-zealand": ["styczen", "luty", "marzec", "grudzien"],
  "bangkok-thailand": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "barcelona-spain": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "berlin-germany": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "grudzien"],
  "bodrum-turkey": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien"],
  "boston-united-states-of-america": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "grudzien"],
  "brussels-belgium": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "grudzien"],
  "budapest-hungary": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "grudzien"],
  "buenos-aires-argentina": ["styczen", "luty", "marzec", "kwiecien", "maj", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "cagliari-italy": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien"],
  "cairo-egypt": ["luty", "marzec", "kwiecien", "maj", "czerwiec", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "cancun-mexico": ["czerwiec", "lipiec", "sierpien", "wrzesien"],
  "cannes-france": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien"],
  "cape-town-south-africa": ["styczen", "luty", "marzec", "listopad", "grudzien"],
  "catania-italy": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien"],
  "chania-greece": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien"],
  "chicago-united-states-of-america": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "grudzien"],
  "colombo-sri-lanka": ["luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "copenhagen-denmark": ["czerwiec", "lipiec", "sierpien", "grudzien"],
  "corfu-greece": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien"],
  "da-nang-vietnam": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "dalaman-turkey": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien"],
  "denpasar-indonesia": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "djerba-tunisia": ["kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik"],
  "doha-qatar": ["marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad"],
  "dubai-united-arab-emirates": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "dublin-ireland": ["czerwiec", "lipiec", "sierpien", "wrzesien", "grudzien"],
  "dubrovnik-croatia": ["luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad"],
  "faro-portugal": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien"],
  "fira-greece": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien"],
  "florence-italy": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "geneva-switzerland": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "grudzien"],
  "goa-india": ["luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "hammamet-tunisia": ["kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik"],
  "helsinki-finland": ["czerwiec", "lipiec", "sierpien", "grudzien"],
  "heraklion-greece": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "hong-kong-hong-kong": ["kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "grudzien"],
  "hurghada-egypt": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "ibiza-town-spain": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien"],
  "istanbul-turkey": ["marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "izmir-turkey": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien"],
  "koh-samui-thailand": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "kos-greece": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien"],
  "krabi-thailand": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "krakow-poland": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "grudzien"],
  "kuala-lumpur-malaysia": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "larnaca-cyprus": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "las-palmas-spain": ["marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "lima-peru": ["styczen", "luty", "marzec", "kwiecien", "maj", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "limassol-cyprus": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien"],
  "lisbon-portugal": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "london-uk": ["marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "los-angeles-united-states-of-america": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "grudzien"],
  "lyon-france": ["marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "madrid-spain": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "malaga-spain": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "male-maldives": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "marrakesh-morocco": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "marseille-france": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien"],
  "melbourne-australia": ["styczen", "luty", "marzec", "kwiecien", "maj", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "mexico-city-mexico": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "grudzien"],
  "miami-united-states-of-america": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "grudzien"],
  "milan-italy": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "montreal-canada": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "grudzien"],
  "munich-germany": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "grudzien"],
  "muscat-oman": ["marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad"],
  "mykonos-town-greece": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien"],
  "naples-italy": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "new-york-united-states-of-america": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "grudzien"],
  "nice-france": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien"],
  "olbia-italy": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien"],
  "osaka-japan": ["kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "grudzien"],
  "oslo-norway": ["czerwiec", "lipiec", "sierpien", "grudzien"],
  "palermo-italy": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien"],
  "palma-spain": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "paphos-cyprus": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien"],
  "paris-france": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "penang-malaysia": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "phuket-thailand": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "piran-slovenia": ["czerwiec", "lipiec", "sierpien"],
  "playa-del-carmen-mexico": ["czerwiec", "lipiec", "sierpien", "wrzesien"],
  "port-louis-mauritius": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "porto-portugal": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "prague-czechia": ["kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "grudzien"],
  "punta-cana-dominican-republic": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "reykjavik-iceland": ["czerwiec", "lipiec", "sierpien", "grudzien"],
  "rhodes-greece": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "rome-italy": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "san-francisco-united-states-of-america": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "grudzien"],
  "san-juan-puerto-rico": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "santa-cruz-de-tenerife-spain": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "sarande-albania": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien"],
  "seoul-south-korea": ["kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "grudzien"],
  "seville-spain": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "sharm-el-sheikh-egypt": ["kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik"],
  "singapore-singapore": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "sliema-malta": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien"],
  "sousse-tunisia": ["kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik"],
  "split-croatia": ["luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad"],
  "st-julian-s-malta": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien"],
  "stockholm-sweden": ["czerwiec", "lipiec", "sierpien", "grudzien"],
  "stone-town-tanzania": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "sydney-australia": ["styczen", "luty", "marzec", "kwiecien", "maj", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "taipei-taiwan": ["kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "grudzien"],
  "tangier-morocco": ["kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik"],
  "tel-aviv-israel": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "tirana-albania": ["czerwiec", "lipiec", "sierpien", "wrzesien"],
  "tokyo-japan": ["kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "grudzien"],
  "toronto-canada": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "grudzien"],
  "valencia-spain": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "valletta-malta": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "vancouver-canada": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "grudzien"],
  "venice-italy": ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"],
  "vienna-austria": ["kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "grudzien"],
  "vlore-albania": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien"],
  "warsaw-poland": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "grudzien"],
  "washington-united-states-of-america": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "grudzien"],
  "zadar-croatia": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien"],
  "zakynthos-greece": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien"],
  "zurich-switzerland": ["maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "grudzien"],
};
