import type { MetadataRoute } from "next";

import { comparisonPairs } from "@/lib/mvp/comparisons";
import { getTopDestinations } from "@/lib/mvp/destinations-seed";
import { getAllDestinationProfiles } from "@/lib/mvp/destinations";
import { polishMonthSlugs, seasonSlugs } from "@/lib/mvp/months";
import { getEditorialArticles, getEditorialCategories } from "@/lib/mvp/publisher-content";
import { getSiteUrl } from "@/lib/mvp/site";

// Sesja C2 — sitemap sources verified destinations from
// data/destinations.json. Up to SEARCH_URL_LIMIT top destinations get
// their own /hotele/szukaj URL so Google can index the search-results
// page per destination. Bumped 500 → 1500 in the Sesja C2 phase-2
// follow-up (TP-resolver + geo-distance harvest yielded ~900
// destinations and room to grow). Above 5k total URLs we'd split into
// sitemap-index; with ~4-5k total we still stay well under that.
const SEARCH_URL_LIMIT = 1500;

export default function sitemap(): MetadataRoute.Sitemap {
  const siteUrl = getSiteUrl();
  const baseLastModified = new Date("2026-05-26T00:00:00.000Z");
  const staticRoutes = [
    "",
    "/hotele",
    "/kierunki",
    "/inspiracje",
    "/przewodniki",
    "/oferta",
    "/faq",
    "/cennik",
    "/city-breaki",
    "/cieple-kierunki",
    "/bez-wizy",
    "/tanie-podroze",
    "/weekendowe-wyjazdy",
    "/mapa-serwisu",
    "/jak-pracujemy",
    "/standard-redakcyjny",
    "/o-nas",
    "/kontakt",
    "/polityka-prywatnosci",
    "/regulamin",
    "/linki-partnerskie",
    "/feed.xml",
  ];

  const categoryRoutes = getEditorialCategories().map((category) => `/${category.slug}`);
  const destinationProfiles = getAllDestinationProfiles();
  const destinationRoutes = destinationProfiles.map((destination) => `/kierunki/${destination.slug}`);
  const articleRoutes = getEditorialArticles().map((article) => `/inspiracje/${article.slug}`);

  // Per-destination search URLs. We URL-encode the city+country pair so
  // the live page renders without an extra resolve round-trip.
  const seedSearchRoutes = getTopDestinations(SEARCH_URL_LIMIT).map((d) => {
    const params = new URLSearchParams({
      destination: d.city.en,
      country: d.country.en,
    });
    return `/hotele/szukaj?${params.toString()}`;
  });

  // Comparison pages — high-intent SEO queries like "barcelona vs valencia".
  const comparisonRoutes = comparisonPairs.map((pair) => `/porownanie/${pair.slug}`);

  // Seasonal best-of pages — 4 URLs (wiosna, lato, jesien, zima). Modest
  // traffic, high relevance for "najlepsze kierunki na lato" queries.
  const seasonRoutes = seasonSlugs.map((season) => `/najlepsze-kierunki/${season}`);

  // Destination × month pages — generated by /kierunki/[slug]/[miesiac].
  // ~ profiles × 12 months. For ~235 destinations this is ~2,800 URLs.
  // We stay under Google's 50k-URL-per-sitemap limit (we'd need 10×+ growth
  // to split into a sitemap-index).
  const monthRoutes = destinationProfiles.flatMap((destination) =>
    polishMonthSlugs.map((month) => `/kierunki/${destination.slug}/${month}`),
  );

  const seenUrls = new Set<string>();
  const entries: MetadataRoute.Sitemap = [];
  const allRoutes = [
    ...staticRoutes,
    ...categoryRoutes,
    ...destinationRoutes,
    ...articleRoutes,
    ...comparisonRoutes,
    ...seasonRoutes,
    ...monthRoutes,
    ...seedSearchRoutes,
  ];

  for (const route of allRoutes) {
    if (seenUrls.has(route)) continue;
    seenUrls.add(route);

    const isSearchRoute = route.startsWith("/hotele/szukaj");
    const isComparisonRoute = route.startsWith("/porownanie/");
    const isSeasonRoute = route.startsWith("/najlepsze-kierunki/");
    const isMonthRoute = /^\/kierunki\/[^/]+\/[^/]+$/.test(route);

    let changeFrequency: "daily" | "weekly" | "monthly";
    let priority: number;

    if (route === "") {
      changeFrequency = "daily";
      priority = 1;
    } else if (route === "/kierunki" || route === "/inspiracje" || categoryRoutes.includes(route)) {
      changeFrequency = "daily";
      priority = 0.9;
    } else if (route.startsWith("/kierunki/") && !isMonthRoute) {
      changeFrequency = "weekly";
      priority = 0.8;
    } else if (route.startsWith("/inspiracje/")) {
      changeFrequency = "weekly";
      priority = 0.75;
    } else if (isComparisonRoute) {
      changeFrequency = "weekly";
      priority = 0.7;
    } else if (isMonthRoute) {
      changeFrequency = "monthly";
      priority = 0.65;
    } else if (isSeasonRoute) {
      changeFrequency = "weekly";
      priority = 0.7;
    } else if (isSearchRoute) {
      changeFrequency = "weekly";
      priority = 0.6;
    } else {
      changeFrequency = "monthly";
      priority = 0.65;
    }

    entries.push({
      url: `${siteUrl}${route}`,
      lastModified: baseLastModified,
      changeFrequency,
      priority,
    });
  }

  return entries;
}
