import type { MetadataRoute } from "next";

import { comparisonPairs } from "@/lib/mvp/comparisons";
import { commercialCitySlugs } from "@/lib/mvp/commercial-cities";
import { getAllDestinationProfiles } from "@/lib/mvp/destinations";
import { polishMonthSlugs, seasonSlugs } from "@/lib/mvp/months";
import { getEditorialArticles, getEditorialCategories } from "@/lib/mvp/publisher-content";
import { getSiteUrl } from "@/lib/mvp/site";

// 2026-05-29 SEO sprint — removed `/hotele/szukaj?...` search URLs
// entirely. Two reasons:
//   1. Search results are dynamic by design; they don't have stable
//      content for Google to rank and risk being judged as low-quality
//      duplicates of the destination guide pages (`/kierunki/[slug]`).
//   2. /hotele/szukaj is now Disallowed in robots.ts — putting it in
//      sitemap was a contradiction Google flagged as a soft signal.
//
// Crawl budget is reallocated to the high-CTR pages that actually
// convert: destination guides, inspiration articles, comparison pages.
// Priorities below favour the pages we want Google to revisit fastest.

export default function sitemap(): MetadataRoute.Sitemap {
  const siteUrl = getSiteUrl();
  const baseLastModified = new Date();
  const staticRoutes = [
    "",
    // "/hotele" intentionally omitted — it 308-redirects to "/" (the homepage
    // is the canonical hotel landing). Listing a redirecting URL would waste
    // crawl budget and split equity.
    "/kierunki",
    "/inspiracje",
    "/przewodniki",
    "/oferta",
    "/faq",
    "/cennik",
    "/city-breaki",
    "/cieple-kierunki",
    "/bez-wizy",
    "/tanie-podroze",
    "/weekendowe-wyjazdy",
    "/mapa-serwisu",
    "/jak-pracujemy",
    "/standard-redakcyjny",
    "/o-nas",
    "/kontakt",
    "/polityka-prywatnosci",
    "/regulamin",
    "/linki-partnerskie",
    "/feed.xml",
  ];

  const categoryRoutes = getEditorialCategories().map((category) => `/${category.slug}`);
  const destinationProfiles = getAllDestinationProfiles();
  const destinationRoutes = destinationProfiles.map((destination) => `/kierunki/${destination.slug}`);
  const articleRoutes = getEditorialArticles().map((article) => `/inspiracje/${article.slug}`);

  // Commercial landing pages — /hotele/w/[miasto] — curated high-volume
  // Polish-search cities. Highest commercial intent → highest priority.
  const commercialCityRoutes = commercialCitySlugs().map((slug) => `/hotele/w/${slug}`);

  // Comparison pages — high-intent SEO queries like "barcelona vs valencia".
  // In the May 2026 GSC sample these averaged 4.4% CTR — well above the
  // site average — so they earn a top-tier priority.
  const comparisonRoutes = comparisonPairs.map((pair) => `/porownanie/${pair.slug}`);

  // Seasonal best-of pages — 4 URLs (wiosna, lato, jesien, zima). Modest
  // traffic, high relevance for "najlepsze kierunki na lato" queries.
  const seasonRoutes = seasonSlugs.map((season) => `/najlepsze-kierunki/${season}`);

  // Destination × month pages — generated by /kierunki/[slug]/[miesiac].
  // ~ profiles × 12 months. For ~235 destinations this is ~2,800 URLs.
  // After GSC review (228 stron "scanned not indexed" in May 2026), these
  // get the LOWEST priority — Google judged many as near-duplicates and
  // we want to focus its crawl budget on guides + articles + comparisons
  // first. Page bodies are being enriched in the same sprint, but the
  // crawl-priority change goes live immediately.
  const monthRoutes = destinationProfiles.flatMap((destination) =>
    polishMonthSlugs.map((month) => `/kierunki/${destination.slug}/${month}`),
  );

  const seenUrls = new Set<string>();
  const entries: MetadataRoute.Sitemap = [];
  const allRoutes = [
    ...staticRoutes,
    ...categoryRoutes,
    ...commercialCityRoutes, // highest commercial-intent pages — front of queue
    ...destinationRoutes,
    ...articleRoutes,
    ...comparisonRoutes,
    ...seasonRoutes,
    ...monthRoutes,
  ];

  for (const route of allRoutes) {
    if (seenUrls.has(route)) continue;
    seenUrls.add(route);

    const isComparisonRoute = route.startsWith("/porownanie/");
    const isSeasonRoute = route.startsWith("/najlepsze-kierunki/");
    const isMonthRoute = /^\/kierunki\/[^/]+\/[^/]+$/.test(route);
    const isCommercialCityRoute = route.startsWith("/hotele/w/");

    let changeFrequency: "daily" | "weekly" | "monthly";
    let priority: number;

    if (route === "") {
      changeFrequency = "daily";
      priority = 1.0;
    } else if (isCommercialCityRoute) {
      // Commercial landing pages — highest revenue potential
      // (head queries "hotele barcelona" et al. at 7-33k mies. PL each).
      changeFrequency = "daily";
      priority = 0.95;
    } else if (route === "/kierunki" || route === "/inspiracje" || categoryRoutes.includes(route)) {
      changeFrequency = "daily";
      priority = 0.95;
    } else if (route.startsWith("/kierunki/") && !isMonthRoute) {
      // Destination guides — highest commercial intent + Google-favoured
      // long-form content. These pages are the spine of our SEO funnel.
      changeFrequency = "weekly";
      priority = 0.9;
    } else if (route.startsWith("/inspiracje/")) {
      // Inspiration articles — long-form, link-worthy. Up from 0.75 →
      // 0.85 because they convert better than month pages on average.
      changeFrequency = "weekly";
      priority = 0.85;
    } else if (isComparisonRoute) {
      // Comparison pages — measured 4.4% CTR in May 2026, double the
      // site average. Up from 0.7 → 0.85.
      changeFrequency = "weekly";
      priority = 0.85;
    } else if (isSeasonRoute) {
      // "Najlepsze kierunki na lato" — high-CTR seasonal queries.
      changeFrequency = "weekly";
      priority = 0.8;
    } else if (isMonthRoute) {
      // Month pages — down from 0.65 → 0.5 per the May 2026 GSC review
      // (228 stron "scanned not indexed"). Stays in sitemap so Google
      // can still index the ones with strong intent match (rate, palermo,
      // etc.), but loses crawl-priority dispute against guides/articles.
      changeFrequency = "monthly";
      priority = 0.5;
    } else {
      changeFrequency = "monthly";
      priority = 0.6;
    }

    entries.push({
      url: `${siteUrl}${route}`,
      lastModified: baseLastModified,
      changeFrequency,
      priority,
    });
  }

  return entries;
}
